[project]
name = "repulsbot"
version = "1.0"
description = "The official bot for the repuls.io discord server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord-py>=2.6.2",
    "dotenv>=0.9.9",
    "psutil>=7.1.3",
]